module: Path
custom_categories:
  - name: Path
    children:
      - Path
      - Pathish
xcodebuild_arguments:
  - UseModernBuildSystem=NO
output:
  ../output
  # output directory is relative to config file… ugh
exclude:
  - Sources/Path+StringConvertibles.swift
